
const HDLD_GEARBOX = "box";

class HDGearBox : HDStorageItem {
	default {
		+Inventory.INVBAR
		+Weapon.WIMPY_WEAPON
		+HDWeapon.DROPTRANSLATION
		+HDWeapon.FITSINBACKPACK
		+HDWeapon.ALWAYSSHOWSTATUS
		+HDWeapon.IGNORELOADOUTAMOUNT
		+HDWeapon.HINDERLEGS

		Weapon.SelectionOrder 1010;

		Tag "$TAG_GEARBOX";
		Inventory.Icon "GRCRA0";
		Inventory.PickupMessage "$PICKUP_GEARBOX";
		scale 0.5;

		// Makes weapon sounds
		// Inventory.PickupSound "misc/w_pkup";

		// Not worn at all.
		HDWeapon.wornlayer 0;
		HDWeapon.refid HDLD_GEARBOX;

		// Heavy, but always predictably so.
		HDStorageItem.MinBulk 500;

		// Nearly infinite storage.
		HDStorageItem.MaxCapacity 100000;
		
		HDStorageItem.MaxBunch 20;

		HDWeapon.loadoutcodes "
		\cu use \".\" to add items like \",\" in the loadout,
		\cu e.g., bak.z66nogl.4505; \"???\" adds a few randoms.";
	}

	// Returns normal weight if under the threshold,
	// Normal weight + excess bulk modified by a percentage after that,
	// A static value after that. 
	override double WeaponBulk() {
		return ContainerBulk(itemBulk);
	}

	//how much space it takes inside another container
	//if we don't do this then things nested inside multiple containers
	//eventually have almost no bulk at all
	override double ContainerBulk(double it) const {

		//     0blk => 500 + ((  0 - 500) * 0.25) => 500 + (-500 * 0.25) => 500 - 125 =>   375
		//   100blk => 500 + ((100 - 500) * 0.25) => 500 + (-400 * 0.25) => 500 - 100 =>   400
		//   200blk => 500 + ((200 - 500) * 0.25) => 500 + (-300 * 0.25) => 500 -  75 =>   425
		//   300blk => 500 + ((300 - 500) * 0.25) => 500 + (-200 * 0.25) => 500 -  50 =>   450
		//   400blk => 500 + ((400 - 500) * 0.25) => 500 + (-100 * 0.25) => 500 -  25 =>   475
		//   500blk => 500 + ((500 - 500) * 0.25) => 500 + (   0 * 0.25) => 500 -   0 =>   500
		//   600blk =>                                                                     600
		//  1000blk =>                                                                    1000
		//  5000blk =>                                                                    5000
		// 10000blk =>                                                                   10000
		return it < minBulk ? (minBulk + ((it - minBulk) * 0.25)) : it;
	}

	// check if an item can be added at all
	override bool CanFitInThisContainer(Class<Inventory> itemType) {
		let item = getDefaultByType(itemType);
		return item && (HDPickup(item) || HDWeapon(item)) && !(item.bNOINTERACTION|item.bUNDROPPABLE|item.bUNTOSSABLE);
	}
	
	// sometimes particular instances of an item may vary
	override bool ThisCanFitInThisContainer(Inventory item) {
		return item && (HDPickup(item) || HDWeapon(item)) && !(item.bNOINTERACTION|item.bUNDROPPABLE|item.bUNTOSSABLE);
	}

	override bool IsBeingWorn() { return false; }

	// TODO: Localize
	override string pickupMessage() {
		string msg = super.pickupMessage();
		double bulk = WeaponBulk();

		if(items.size() < 1 && !owner) {
			switch (random(0, 6)) {
				case 0:
					msg = msg.." Best not to look inside too long...";
					break;
				case 1:
					msg = msg.." What a feat of engineering!";
					break;
				case 2:
					msg = msg.." If only you could fit inside.";
					break;
				default:
					break;
			}
		} else if (bulk <= MinBulk) {
			switch (random(0, 10)) {
				case 0:
					msg = msg.." It's as ergonomic as it looks...";
					break;
				default:
					break;
			}
		} else if (bulk >= MinBulk * 2) {
			switch (random(0, 10)) {
				case 0:
					msg = msg.." A black hole in your pocket.";
					break;
				case 1:
					msg = msg.." You have a serious problem.";
					break;
				case 2:
					msg = msg.." None shall escape it.";
					break;
				default:
					break;
			}
		} else if (bulk > MinBulk) {
			switch (random(0, 10)) {
				case 0:
					msg = msg.." It feels warm to the touch.";
					break;
				case 1:
					msg = msg.." Ah, hoard sweet hoard.";
					break;
				default:
					break;
			}
		}

		return msg;
	}

	states(actor) {
		spawn:
			GRCR AB -1 nodelay {
				if (items.size() < 1) {
					frame = 0;
				} else if (target) {
					translation = target.translation;
					frame = 1;
				}
			}
			stop;
	}
}

//semi-filled gear crates at random
class WildGearBox : IdleDummy {
		//$Category "Items/Hideous Destructor/Gear"
		//$Title "Gear Crate (Random Spawn)"
		//$Sprite "GRCRA0"
	override void postBeginPlay() {
		super.postBeginPlay();

		let aaa = HDGearBox(spawn("HDGearBox", pos, ALLOW_REPLACE));
		aaa.RandomContents('HDCoreStorageItemList', frandom(0.001, 0.01), false);

		HDF.TransferSpecials(self, aaa);
		
		destroy();
	}
}
